/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           |
     \\/     M anipulation  |
-------------------------------------------------------------------------------
\*---------------------------------------------------------------------------*/

#include "radexWrite.H"
#include "addToRunTimeSelectionTable.H"
#include "volFields.H"
#include "uniformDimensionedFields.H"
#include "Pstream.H"
#include "functionObjectList.H"
#include "functionObjectProperties.H"
#include "profilingTrigger.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{
namespace functionObjects
{

defineTypeNameAndDebug(radexWrite, 0);
addToRunTimeSelectionTable(functionObject, radexWrite, dictionary);

} // End namespace functionObjects
} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

Foam::functionObjects::radexWrite::radexWrite
(
    const word& name,
    const Time& runTime,
    const dictionary& dict
)
:
    radexBase(name, runTime, dict)
{
    read(dict);
}


bool Foam::functionObjects::radexWrite::execute()
{
    return true;
}


bool Foam::functionObjects::radexWrite::write()
{
    return processFields();
}


bool Foam::functionObjects::radexWrite::end()
{
    const bool ok = write();

    if (Pstream::master())
    {
        return writeFinalStep() && ok;
    }

    return ok;
}


radex::data::OutgoingHandle Foam::functionObjects::radexWrite::makeHandle
(
    const word& fieldName,
    label subdomainId
) const
{
    return radex::data::OutgoingHandle(makeKey(fieldName, subdomainId));
}


bool Foam::functionObjects::radexWrite::processScalarField
(
    const word& fieldName,
    label subdomainId
)
{
    addProfiling(radexWriteScalarField, "radexWrite::writeScalarField(", fieldName, ")");

    const radex::data::OutgoingHandle handle = makeHandle(fieldName, subdomainId);

    io_.put(handle, mesh_.lookupObject<volScalarField>(fieldName));

    return true;
}


bool Foam::functionObjects::radexWrite::processVectorField
(
    const word& fieldName,
    label subdomainId
)
{
    addProfiling(radexWriteVectorField, "radexWrite::writeVectorField(", fieldName, ")");

    const radex::data::OutgoingHandle handle = makeHandle(fieldName, subdomainId);

    io_.put(handle, mesh_.lookupObject<volVectorField>(fieldName));

    return true;
}


bool Foam::functionObjects::radexWrite::processUniformScalar
(
    const word& fieldName,
    label subdomainId
)
{
    addProfiling(radexWriteUniformScalar, "radexWrite::writeUniformScalar(", fieldName, ")");

    const radex::data::OutgoingHandle handle = makeHandle(fieldName, subdomainId);

    if (mesh_.foundObject<uniformDimensionedScalarField>(fieldName))
    {
        const auto& f =
            mesh_.lookupObject<uniformDimensionedScalarField>(fieldName);

        addProfiling(radexWriteUniformScalarPut, "radexWrite::put_scalar(", fieldName, ")");

        io_.put(handle, f.value());

        return true;
    }

    // Not a registered field object - look for a result stored by another
    // function object (e.g. surfaceFieldValue), which are kept in the
    // function-object properties/results dictionary rather than the
    // objectRegistry. The entry name is auto-generated by the producing
    // function object (e.g. "areaAverage(inlet,p)"), not user-configurable.
    const auto& propsDict = mesh_.time().functionObjects().propsDict();
    const wordList entries(propsDict.objectResultEntries(fieldName));

    if (entries.empty())
    {
        WarningInFunction
            << "Scalar " << fieldName
            << " not found as a registered field or function object result"
            << "; skipping" << nl;
        return false;
    }

    if (entries.size() > 1)
    {
        WarningInFunction
            << "Function object " << fieldName << " has " << entries.size()
            << " result entries; only the first (" << entries.first()
            << ") will be exported" << nl;
    }

    scalar value;
    if (!propsDict.getObjectResult<scalar>(fieldName, entries.first(), value))
    {
        WarningInFunction
            << "Result " << entries.first() << " of function object "
            << fieldName << " is not a scalar; skipping" << nl;
        return false;
    }

    if (Pstream::master())
    {
        addProfiling(radexWriteResultScalarPut, "radexWrite::put_scalar(", fieldName, ")");

        io_.put(handle, value);
    }

    return true;
}


bool Foam::functionObjects::radexWrite::writeFinalStep()
{
    const radexKey key("final_step");

    io_.put(key.outgoing(), mesh_.time().value());

    Info<< type() << " " << key.str()
        << ": wrote final_step from "
        << Pstream::myProcNo() << nl;

    return true;
}


// ************************************************************************* //
